version: '3.9'

volumes:
  sport_application_postgres_data:
    driver: local

services:
  postgres:
    container_name: sport_application_postgres_container
    image: postgres:15
    volumes:
      - sport_application_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sportuser
      POSTGRES_PASSWORD: sportuser
    ports:
      - "5432:5432"

